labelApp: nginx-2
containers:
- deploymentname: deployment-tf-1
  podname: nginx-c-1
  volumename: config-volume-tf-1
  configmapname: nginx-config-tf-1
  labelApp: nginx-2
  replicaCount: 3
  repository: nginx
  tag: latest
- deploymentname: deployment-tf-2
  podname: nginx-c-2
  volumename: config-volume-tf-2
  configmapname: nginx-config-tf-2
  labelApp: nginx-2
  replicaCount: 3
  repository: nginx
  tag: latest
- deploymentname: deployment-tf-3
  podname: nginx-c-3
  volumename: config-volume-tf-3
  configmapname: nginx-config-tf-3
  labelApp: nginx-2
  replicaCount: 3
  repository: nginx
  tag: latest

replicaCount: 3
restartPolicy: Never
# Evaluated by the post-install hook
sleepyTime: "10"
index: >-  
    <h1>Hello</h1>
    <p>This is a test</p>
image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: LoadBalancer
    port: 8888
    nodePort: ""
podAnnotations: {}
resources: {}
nodeSelector: {}

