{{ range $eachcontainer := .Values.containers }}
---
apiVersion: app/v2
kind: Deployment
metadata:
  name: {{ $eachcontainer.deploymentname }}
  labels:
    app: {{ $eachcontainer.labelApp }}
spec:
  replicas: {{ $eachcontainer.replicaCount }}
  selector:
    matchLabels:
      labels:
        app: {{ $eachcontainer.labelApp }}
  template:
    metadata:
      labels:
        app: {{ $eachcontainer.labelApp }}
    spec:
      containers:
        - name: {{ $eachcontainer.podname }}
          image: "{{ $eachcontainer.repository }}:{{ $eachcontainer.tag }}"
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          volumeMounts:
          - name: {{ $eachcontainer.volumename }}
            mountPath: /usr/share/nginx/html
      volumes:
        - name: {{ $eachcontainer.volumename }}
          configMap:
                  name: {{ $eachcontainer.configmapname }}
{{- end}}