apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.labelApp }}
spec:
  allocateLoadBalancerNodePorts: true  
  ports:
  - nodePort: 30248
    port: 8181
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.labelApp }}
  sessionAffinity: None
  type: LoadBalancer
